cpufreq: schedutil: Fix setting policy limits when frequency tables are used [2/3]
Subsequent to 15888cd ("cpufreq: Fix setting policy limits when frequency tables are used")

This resolves the following compilation error:

In file included from ../kernel/sched/build_utility.c:69:
../kernel/sched/cpufreq_schedutil.c: In function 'get_next_freq':
../kernel/sched/cpufreq_schedutil.c:203:15: error: too few arguments to function 'cpufreq_frequency_table_target'
  203 |         idx = cpufreq_frequency_table_target(policy, freq, CPUFREQ_RELATION_H);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../kernel/sched/build_utility.c:22:
../include/linux/cpufreq.h:1064:19: note: declared here
 1064 | static inline int cpufreq_frequency_table_target(struct cpufreq_policy *policy,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>